Repository COS301-SE-2022/Image-Converter, pull requests merged in 2022-07, with the labels that each got.

#56 Feature/back end GitHub actions
  .gitignore
  Server/app.py
  Server/config_default.py
  Server/database/mockDatabase.py
  Server/images/original/Graph.png
  Server/test/Intergration-Tests/__init__.py
  Server/test/Intergration-Tests/test_delete_history.py
  Server/test/Intergration-Tests/test_getImage.py
  Server/test/Intergration-Tests/test_insertFeeaback.py
  Server/test/Intergration-Tests/test_insertImage.py
  Server/test/Intergration-Tests/test_login.py
  Server/test/Intergration-Tests/test_register.py
  Server/test/Unit-Tests/__init__.py
  Server/test/Unit-Tests/test_getUserWithEmail.py
  Server/test/Unit-Tests/test_getUserWithId.py
  Server/test/__pycache__/test_routes.cpython-310-pytest-7.1.2.pyc
  Server/test/__pycache__/test_templatematching.cpython-310-pytest-7.1.2.pyc
  Server/test/test_delete_history.py
  Server/test/test_getImage.py
  Server/test/test_insertImage.py
  Server/test/test_login.py
  Server/test/test_register.py
  Server/test/test_routes.py
  Server/test/test_smoothing.py
  Server/test/test_templatematching.py
Labels: High, test

#57 ✅ (Front-End) Testing the Converter Component
  Front-End/Image-Converter/src/app/app.component.spec.ts
  Front-End/Image-Converter/src/app/app.component.ts
  Front-End/Image-Converter/src/app/converter/converter.component.spec.ts
Labels: test

#89 Feature/demo3 final
  Front-End/Image-Converter/src/app/img-classifier/img-classifier.component.html
  Front-End/Image-Converter/src/app/img-classifier/img-classifier.component.scss
  Front-End/Image-Converter/src/app/img-classifier/img-classifier.component.spec.ts
  Front-End/Image-Converter/src/app/img-classifier/img-classifier.component.ts
Labels: bug, Frontend, test
