Repository COS301-SE-2022/Image-Converter, pull requests merged in 2022-09, with the labels that each got.

#116 picture gets saved in the data sets
  .gitignore
  Front-End/Image-Converter/src/app/shared/converter.service.ts
  Front-End/Image-Converter/src/app/unrecognized-images/unrecognized-images.component.ts
  Server/app.py
  Server/database/__pycache__/database.cpython-310.pyc
  Server/testImage.py
Labels: API, High, Frontend, Backend

#117 Updated UI
  Front-End/Image-Converter/package-lock.json
  Front-End/Image-Converter/package.json
  Front-End/Image-Converter/src/app/app-routing.module.ts
  Front-End/Image-Converter/src/app/converter/converter.component.html
  Front-End/Image-Converter/src/app/converter/converter.component.scss
  Front-End/Image-Converter/src/app/live-graphing2/live-graphing2.component.scss
  Front-End/Image-Converter/src/app/nav/nav-route/nav-route-routing.module.ts
  Front-End/Image-Converter/src/app/nav/nav.component.html
  Front-End/Image-Converter/src/app/nav/nav.component.scss
  Front-End/Image-Converter/src/app/nav/nav.component.ts
  Front-End/Image-Converter/tsconfig.app.json
  Front-End/Image-Converter/tsconfig.json
Labels: enhancement, API, High, Frontend, Backend

#118 Graph endpoint
  Front-End/Image-Converter/src/app/conversion/conversion.component.ts
  Front-End/Image-Converter/src/app/converter/converter.component.scss
  Front-End/Image-Converter/src/app/filter/filter.component.html
  Front-End/Image-Converter/src/app/filter/filter.component.ts
Labels: High

#127 Feature/fix UI
  .github/workflows/pythonTests.yml
  Front-End/Image-Converter/src/app/login/login.component.ts
  Server/app.py
  Server/config_default.py
  Server/database/__pycache__/database.cpython-310.pyc
  Server/database/database.py
  Server/database/firebase.py
  Server/requirements.txt
  Server/test/__pycache__/test_routes.cpython-310-pytest-7.1.2.pyc
  Server/test/test_routes.py
Labels: enhancement, API, Database, Frontend, Backend

#139 Changes on UI and Model
  Front-End/Image-Converter/src/app/admin-image-pop-up/admin-image-pop-up.component.html
  Front-End/Image-Converter/src/app/admin-image-pop-up/admin-image-pop-up.component.scss
  Front-End/Image-Converter/src/app/unrecognized-images/unrecognized-images.component.html
  Front-End/Image-Converter/src/app/unrecognized-images/unrecognized-images.component.scss
  Server/converter/model_training.py
  Server/converter/multiclass_integ.py
Labels: High

#140 Changed register placeholder
  Front-End/Image-Converter/src/app/conversion/conversion.component.html
  Front-End/Image-Converter/src/app/conversion/conversion.component.scss
  Front-End/Image-Converter/src/app/dashboard/dashboard.component.scss
  Front-End/Image-Converter/src/app/filter/filter.component.html
  Front-End/Image-Converter/src/app/filter/filter.component.scss
  Front-End/Image-Converter/src/app/landing-page/landing-page.component.scss
  Front-End/Image-Converter/src/app/register/register.component.html
  Server/converter/model_training.py
  Server/converter/multiclass_integ.py
Labels: Frontend
