Repository COS301-SE-2022/Image-Converter, pull requests merged in 2022-10, with the labels that each got.

#174 Feature/re demo upload
  Front-End/Image-Converter/src/app/converter/converter.component.html
  Front-End/Image-Converter/src/app/converter/converter.component.scss
  Front-End/Image-Converter/src/app/converter/converter.component.ts
  Front-End/Image-Converter/src/app/filter/filter.component.html
  Front-End/Image-Converter/src/app/filter/filter.component.scss
  Front-End/Image-Converter/src/app/filter/filter.component.ts
  Front-End/Image-Converter/src/app/image-popup/image-popup.component.html
  Front-End/Image-Converter/src/app/image-popup/image-popup.component.scss
  Front-End/Image-Converter/src/app/shared/component-communication.service.ts
Labels: High, Frontend

#179 Added get image
  Front-End/Image-Converter/src/app/converter/converter.component.ts
  Front-End/Image-Converter/src/app/login/login.component.ts
  Front-End/Image-Converter/src/app/shared/converter.service.ts
  Server/app.py
  Server/database/database.py
  Server/images/original/Converted.png
Labels: API, Database, High, Backend

#184 💄(html/css): Fixing upload page
  Front-End/Image-Converter/src/app/conversion/conversion.component.html
  Front-End/Image-Converter/src/app/conversion/conversion.component.scss
  Front-End/Image-Converter/src/app/converter/converter.component.html
  Front-End/Image-Converter/src/app/converter/converter.component.scss
  Front-End/Image-Converter/src/app/filter/filter.component.html
  Front-End/Image-Converter/src/app/filter/filter.component.scss
  Front-End/Image-Converter/src/app/footer/footer.component.scss
  Front-End/Image-Converter/src/app/nav/nav.component.html
Labels: High, Frontend

#190 Featurer/img tags
  Front-End/Image-Converter/src/app/app.module.ts
  Front-End/Image-Converter/src/app/conversion/conversion.component.html
  Front-End/Image-Converter/src/app/conversion/conversion.component.ts
  Front-End/Image-Converter/src/app/converter/converter.component.ts
  Front-End/Image-Converter/src/app/gallery-images/filter.pipe.ts
  Front-End/Image-Converter/src/app/gallery-images/gallery-images.component.html
  Front-End/Image-Converter/src/app/gallery-images/gallery-images.component.scss
  Front-End/Image-Converter/src/app/gallery-images/gallery-images.component.ts
  Front-End/Image-Converter/src/app/nav/nav-route/nav-route.module.ts
  Front-End/Image-Converter/src/app/shared/converter.service.ts
  Server/app.py
  Server/converter/ConvertFomat.py
  Server/converter/test.py
  Server/database/database.py
Labels: Backend

#191 Changed the name of one the get image methods
  Server/app.py
  Server/database/database.py
Labels: Database, Backend
